# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: flask-mongo-app

---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-mongo-config
  namespace: flask-mongo-app
data:
  FLASK_ENV: development
  FLASK_RUN_HOST: 0.0.0.0
  MONGO_URI: mongodb://mongodb:27017/

---
# PersistentVolumeClaim for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: flask-mongo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Deployment for MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: flask-mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: ersanjeev/web1
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_DATABASE
          value: ping_database
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc

---
# Service for MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: flask-mongo-app
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None

---
# Deployment for Flask App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ersanjeev/web1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-mongo-config

---
# Service for Flask App
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-mongo-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer


  ---
# Secrets for Flask App
apiVersion: v1
kind: Secret
metadata:
  name: regcred  # Name of the secret
  namespace: prod
type: kubernetes.io/dockerconfigjson  # Type for Docker registry secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpYSnpZVzVxWldWMk9rRmhhR0Z1WVdGb1lXNGlOREV4IgoJCX0KCX0KfQ==  # Replace with your base64 string



