apiVersion: v1
kind: ConfigMap
metadata:
  name: application-env-variable
data:
  MONGO_URI: "mongodb://mongodb:27017/"
  MONGO_INITDB_DATABASE: "ping_database"
# Flask Configuration
  FLASK_APP: "app.py"
  FLASK_ENV: "development"
  FLASK_DEBUG: "1"

