apiVersion: v1
kind: ConfigMap
metadata:
  name: application-env-variable
data:
  ENVIRONMENT: "DEV"
  HOST: "localhost"
  PORT: "8000"
  MONGODB_HOST: mongodb-service
  MONGODB_PORT: "27017"
  MONGODB: "0"