apiVersion: v1
kind: ConfigMap
metadata:
  name: application-env-variable
  namespace: prod
data:
  MONGO_URI: "mongodb://172.31.17.192:30085/"
  MONGO_INITDB_DATABASE: "ping_database"
# Flask Configuration
  FLASK_APP: "app.py"
  FLASK_ENV: "development"
  FLASK_DEBUG: "1"
  

