apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongodb-env-variable  # Reference the ConfigMap for non-sensitive envs