apiVersion: v1
kind: Secret
metadata:
  name: regcred  # Name of the secret
  namespace: default  # Namespace (you can change this if needed)
type: kubernetes.io/dockerconfigjson  # Type for Docker registry secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpYSnpZVzVxWldWMk9rRmhhR0Z1WVdGb1lXNGlOREV4IgoJCX0KCX0KfQ==  # Replace with your base64 string


  