name: Build and Publish to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Set to "latest" for main branch, or branch name for other branches
  IMAGE_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
  DOCKER_REPO: ersanjeev/task1  # Replace with your Docker Hub repository

jobs:
  build-and-publish:
    name: Build and Publish to Docker Hub
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Infer Tag from Branch
        id: infer-tag
        # Get the branch name from the ref, and replace / with - to make it a valid tag
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          if [[ $BRANCH_NAME == "main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=$(echo $BRANCH_NAME | sed -e 's/\//-/g')" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # Update path if Dockerfile is not in ./docker/
          pull: true
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ steps.infer-tag.outputs.tag }},
            ${{ env.DOCKER_REPO }}:${{ github.sha }}

      - name: update kube config
        run: aws eks update-kubeconfig --region eu-central-1 --name three-tier-cluster

      - name: Deploy to EKS
        run: |
          
          kubectl apply -f ./k8s-manifests/application-deployment.yml 
